version: '3.8'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: mpc-redisjson
    ports:
      - "6379:6379"
    volumes:
      - rejson_data:/data
    networks:
      - pythonrq-network
  worker:
    image: pythonrqworker:latest
    #container_name: mpc-worker
    hostname: mpc-worker
    depends_on:
      - redis
    networks:
      - pythonrq-network
    deploy:
      replicas: 3

volumes:
  rejson_data:

networks:
  pythonrq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24
          gateway: 192.168.21.1