version: '3.8'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: mpc-redisjson
    ports:
      - "6379:6379"
    volumes:
      - rejson_data:/data
    networks:
      - pythonrq-network
  mpc-worker-1:
    image: pythonrqworker:latest
    container_name: mpc-worker-1
    ports:
      - "7000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - pythonrq-network
  mpc-worker-2:
    image: pythonrqworker:latest
    container_name: mpc-worker-2
    ports:
      - "7001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - pythonrq-network
  mpc-worker-3:
    image: pythonrqworker:latest
    container_name: mpc-worker-3
    ports:
      - "7002:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - pythonrq-network  

volumes:
  rejson_data:

networks:
  pythonrq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24
          gateway: 192.168.21.1